### ISSUE TITLE
Error: Parameter token or opts.auth is required

### ISSUE THREAD

**Issue by dtamez** [SvanBoxel/org-audit-action#81]
Receiving the error "Parameter token or opts.auth is required" when running an example configuration on a test organization and repo.  Attached are the yaml file (renamed .txt for upload) and the action output.
[err.log](https://github.com/SvanBoxel/org-audit-action/files/4610762/err.log)
[main.yml.txt](https://github.com/SvanBoxel/org-audit-action/files/4610768/main.yml.txt)

**Comment by devang-houzz** [comment]
What was the solution here? I’m running into the same issue.
